qdrant_url = "http://localhost:6334"

# 代理配置
[agent]
api_key = "sk-33e3643fd6db453c9015697413b44bae"
preamble = "你是公司的的智能客服，请你根据我提供的文档进行回答，如果文档中没有相关信息，请根据你的知识库回答，你需要时刻关注用户的情绪，如果发现用户开始焦急或者生气了，立刻回复一个链接告诉可以进行人工处理"
chat_model = "qwen-plus"

# 嵌入模型配置（可选）
[embedding]
api_key = "sk-33e3643fd6db453c9015697413b44bae"
model = "text-embedding-v1"
dimensions = 1536
collection_name = "documents"


# 文档配置
[document]
# 文档类目配置
[[document.categories]]
name = "客服"
directory = "./docs"
collection_name = "kefu"
